jobs:
  build:
    name: Branch CI
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        server-password: GITHUB_TOKEN
        server-username: GITHUB_ACTOR
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
      name: Maven Build
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Ddockerfile.skip=true
        -B -V
    - continue-on-error: true
      name: Maven Verify
      run: 'sudo echo "127.0.0.1 $(eval hostname)" | sudo tee -a /etc/hosts

        mvn verify -B

        '
name: Branch CI
on:
  repository_dispatch:
    types: trigger-ga___branch-ci.yml
